services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenapp-core-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=tenapp-db.cd08g2oc4b37.us-east-2.rds.amazonaws.com;Port=5432;Database=tenapp_db;Username=postgres;Password=postgrespass
    ports:
      - "8080:8080"
