// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TenappCore.Data;

#nullable disable

namespace TenappCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529190000_AddUserPhoneNumber")]
    partial class AddUserPhoneNumber
    {
    }
}
